{% set name = "Orange3-WorldHappiness" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91619820dcb22e606e6a9caf5b3d66843eb2cc7697f670853d9c381bc465ff6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - Orange3 >=3.31
    - pandas
    - pymongo
    - wbgapi
    - dnspython

test:
  imports:
    - orangecontrib.worldhappiness
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/biolab/orange3-world-happiness
  summary: 'Orange3 add-on for accessing socioeconomic data'
  description: |
    Orange3 World Happiness add-on for the Orange3 data mining suite.
    Enables downloading of socioeconomic data from database filled 
    from various economic databases.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  dev_url: https://github.com/biolab/orange3-world-happiness

extra:
  recipe-maintainers:
    - NejcHirci
    - PrimozGodec
